//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahangdienthoai
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhapChiTiet
    {
        public int MaHDNCT { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> MaDT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DienThoai DienThoai { get; set; }
        public virtual HoaDonNhap HoaDonNhap { get; set; }
    }
}
