//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahangdienthoai
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomQuyenChiTiet
    {
        public int MaNQChitiet { get; set; }
        public string Ten_hanhdong { get; set; }
        public string Ma_hanhdong { get; set; }
        public int MaNhomQuyen { get; set; }
    
        public virtual NhomQuyen NhomQuyen { get; set; }
    }
}
